server:
  port: 8086
 
 
spring:
  application:
    name: API-GATEWAY
    
  cloud:  
    gateway:
      mvc:
        routes:
        - id: USER-SERVIVE
          uri: lb://USER-SERVICE
          predicates:
          - Path=/users/**
            
            
        - id: RATING-SERVIVE
          uri: lb://RATING-SERVICE
          predicates:
          - Path=/rating/**
          
          
        - id: HOTEL-SERVIVE
          uri: lb://HOTEL-SERVICE
          predicates:
          - Path=/hotels/**,/staffs/**
  eureka:
    instance:
      prefer-ip-address: true
  Client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    
