server:
  port: 8085
  

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Hotelmicroservices
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
    
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibenate:
          dialect: org.hibernate.dialect.PostgreSQL81Dialect
  application:
    name: HOTEL-SERVICE
          
  eureka:
    instance:
      prefer-ip-address: true
  Client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    
    