server:
  port: 8083
  
spring:
   datasource:
    url: jdbc:postgresql://localhost:5432/RatingServices
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
   jpa:
       hibernate:
          ddl-auto: update
       show-sql: true
       properties:
        hibenate:
          dialect: org.hibernate.dialect.PostgreSQL81Dialect
   application:
     name: RATING-SERVICE 
      
   eureka:
      instance:
        prefer-ip-address: true
    
   Client:
       fetch-registry: true
        register-with-eureka:true
       service-url:
          defaultZone: http://localhost:8761/eureka
  
  